### ISSUE TITLE
add form fields

### ISSUE THREAD

**Issue by numerogeek** [Seekdesign/reseau_freelance#1]
hello,

could you please add the form fields : 
Nom
Prenom
Date de naissance (optionnel)
Freelance en ... ?

Also, change the text into 
Votre inscription nous aide à obtenir plus d'avantages, et à vous tenir informé des nouveaux avantages.
C'est gratuit et tout le monde peut participer à l'initiative

thank you !

**Comment by Seekdesign** [comment]
Added feature.
