### ISSUE TITLE
Subscription confirmation

### ISSUE THREAD

**Issue by numerogeek** [Seekdesign/reseau_freelance#2]
Hello,

could you please add the following texte in the modal when someone register in : 

Merci pour votre inscription, vous allez recevoir une invitation slack pour faire parti du reseau Freelance Connection.
Plus nous sommes nombreux, plus il sera simple d'obtenir des avantages : invitez vos amis ! 

-> and then add a facebook and twitter share button

Thank you !

**Comment by Seekdesign** [comment]
Added feature.
